language: node_js

dist: trusty
sudo: required

node_js:
  - "6"
  - "7"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgs-dev
      - g++-4.8