language: node_js
node_js:
  - "6"
  - "8"

env:
  - CXX=g++-4.8

sudo: true
dist: trusty

before_install:
  - wget http://fr.archive.ubuntu.com/ubuntu/pool/main/g/ghostscript/ghostscript-x_9.18~dfsg~0-0ubuntu2.6_amd64.deb
  - sudo dpkg -i ghostscript-x_9.18~dfsg~0-0ubuntu2.6_amd64.deb
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-4.8 cmake -y
  