language: node_js
node_js:
  - "6"
  - "8"

env:
  - CXX=g++-4.8

sudo: true
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libgs-dev
      - cmake
