language: node_js
node_js:
  - "6"
  - "8"

env:
  - CXX=g++-4.8

sudo: true
dist: trusty
before_install:
  - wget http://archive.ubuntu.com/ubuntu/pool/main/g/ghostscript/ghostscript_9.18~dfsg~0-0ubuntu2.6_amd64.deb
  - sudo dpkg -i ghostscript_9.18~dfsg~0-0ubuntu2.6_amd64.deb

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - cmake
