sudo: required

services:
  - docker

before_install:
  - docker pull ubuntu:xenial
  - docker build -t ubuntu-node test

script:
  - docker run -it -v "$PWD:/app" ubuntu-node bash -i -c "cd app && npm install && npm test"
